server:
  port: 8080
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.h2.H2ConsoleAutoConfiguration
  datasource:
    hikari:
      user:
        username: root
        password: 12345678
        jdbc-url: jdbc:mysql://localhost:3305/users
      sns:
        username: root
        password: 12345678
        jdbc-url: jdbc:mysql://localhost:3305/sns
security:
  oauth2:
    resource:
      id: test
  salt: A0A0A19C3F1A9QQO9REQ3FV928RDS#KK
logging:
  config: classpath:logback-dev.xml
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: DEBUG
    org.springframework.jdbc.core: TRACE
    org.springframework.transaction: INFO
