server:
  port: 8080
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.h2.H2ConsoleAutoConfiguration
  datasource:
    hikari:
      user:
        username: root
        password: 1234
        jdbc-url: jdbc:mysql://localhost:3306/users
      sns:
        username: root
        password: 1234
        jdbc-url: jdbc:mysql://localhost:3306/sns
security:
  oauth2:
    resource:
      id: test
  salt: A0A0A19C3F1A9QQO9REQ3FV928RDS#KK
