### create user
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "email": "test1@gmail.com",
  "password": "12345678",
  "name": "tester"
}

### authorization
POST http://localhost:8080/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic c25zLXdlYi1zZXJ2aWNlOm15LXRlc3Qtc2VydmljZQ

grant_type=password&username=test2223@gmail.com&password=12345678

### refresh token
POST http://localhost:8080/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic c25zLXdlYi1zZXJ2aWNlOm15LXRlc3Qtc2VydmljZQ

grant_type=refresh_token&refresh_token=fec263ba-77d6-4e34-ba7a-8ab43b899f9a

### get user profile
GET http://localhost:8080/api/v1/users/me
Content-Type: application/json
Authorization: bearer 20b98c56-176a-4ba7-a9b5-c8f99a728bf2
###
